---
# Ansible cloud tools for lab based deployments
# Copyright (C) 2020  Kevin Carter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

- name: Update the PowerTools config
  become: true
  ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: "{{ item.backup | bool }}"
  loop: "{{ tripleo_sdk_repos }}"

- name: TripleO repositories setup
  become: true
  block:
    - name: Fetch latest repo version
      uri:
        url: https://trunk.rdoproject.org/{{ (ansible_distribution | lower) }}{{ ansible_distribution_major_version }}/current/delorean.repo
        return_content: yes
      register: tripleo_packages

    - name: Create default repo file
      copy:
        content: "{{ tripleo_packages.content }}"
        dest: /etc/yum.repos.d/delorean.repo

    - name: Install tripleo-repos package
      package:
        name: "python*tripleo-repos"
        state: present

    - name: Run tripleo-repos
      command: tripleo-repos --branch {{ tripleo_sdk_developer_branch }} {{ tripleo_sdk_developer_repos }}
