---

- name: Fetch url data
  uri:
    url: "{{ item.url }}"
    return_content: yes
  register: _package

- name: Install package
  set_fact:
    tripleo_sdk_external_packages: |-
      {% set _ = tripleo_sdk_external_packages.append(
          item.url ~ '/' ~ (_package.content | regex_search('\"(' ~ item.name ~ '.*rpm)\"', multiline=True)).strip('\"')
        )
      %}
      {{ tripleo_sdk_external_packages }}
